version: "3"
services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - cards-nw
    restart: on-failure
  backend:
    image: jov96/cards-api:latest
    # Uncomment below lines if you want docker to build the image locally and use it
    # build:
    #   context: ./api
    networks:
      - cards-nw
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    ports:
      - 8000:8000
    depends_on:
      - db
    restart: on-failure
  ui:
    image: jov96/cards-ui:latest
    # Uncomment below lines if you want docker to build the image locally and use it
    # build:
    #   context: ./ui
    networks:
      - cards-nw
    environment:
      - API_HOST=backend
      - API_PORT=8000
    ports:
      - 8080:80
    depends_on:
      - backend
    restart: on-failure
  pgadmin:
      image: dpage/pgadmin4:5.6
      environment:
        - PGADMIN_DEFAULT_EMAIL=foo@bar.com
        - PGADMIN_DEFAULT_PASSWORD=pgadmin
      volumes:
        - ./servers.json:/pgadmin4/servers.json
      ports:
        - "${PGADMIN_PORT:-5050}:80"
      networks:
        - cards-nw
      restart: on-failure
networks:
  cards-nw:
    driver: bridge
